---
name: ☸ CI

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - name: 🧹 Lint
        uses: pre-commit/action@v3.0.1

  test:
    name: 🧪 Test (${{ matrix.chart }})
    runs-on: ubuntu-latest
    needs:
      - lint

    strategy:
      matrix:
        include:
          - chart: workspace
            has_deps: true
            has_generate: true
            has_tests: true

          - chart: workspace-project
            has_deps: false
            has_generate: false
            has_tests: true

          - chart: workspace-system
            has_deps: true
            has_generate: false
            has_tests: true

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - name: ☸ Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.17.3

      - name: 🔌 Install helm-unittest plugin
        if: matrix.has_tests
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.0.2

      - name: 🔌 Add repo and build dependencies
        if: matrix.has_deps
        run: |
          helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts --force-update
          helm repo add traefik https://traefik.github.io/charts --force-update
          helm dependency build charts/${{ matrix.chart }}/

      - name: 📦 Install yq
        if: matrix.has_generate
        uses: mikefarah/yq@master

      - name: 🔄 Generate files
        if: matrix.has_generate
        run: charts/${{ matrix.chart }}/scripts/generate.sh

      - name: 🧪 Run tests
        if: matrix.has_tests
        run: helm unittest -f "tests/**/*.yaml" ./charts/${{ matrix.chart }}

  e2e:
    name: 🌐 E2E / Network Policies
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - name: ☸ Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.17.3

      - name: 🔧 Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true

      - name: 🧪 Run e2e tests
        run: e2e/e2e.sh all
